### ISSUE TITLE
Hyper v2 compatibility

### ISSUE THREAD

**Issue by chabou** [AlexanderPinkerton/hyper-bloodbath#1]
Great job

Please take a look at my PR to make `hyperpower` compatible with our upcoming v2: https://github.com/zeit/hyperpower/pull/52

**Comment by AlexanderPinkerton** [comment]
Thanks! Will do.

**Comment by AlexanderPinkerton** [comment]
I replicated your changes [in this branch](https://github.com/AlexanderPinkerton/hyper-bloodbath/commit/f60e3a2eb0c96e29471ab7cbeda02909588e0ac7) and it works in V2.

However, I have noticed that even after building a dist, the rendering in V2 seems to be far less smooth and the rendering stutters. Any ideas as to why?

**Comment by chabou** [comment]
I think this is due to electron 1.8 (Chrome v59): https://github.com/electron/electron/issues/11051

**Comment by chabou** [comment]
Can you try our last Canary (2.1.0-canary.1) and give me your feedback?

**Comment by AlexanderPinkerton** [comment]
I will do this very soon

**Comment by AlexanderPinkerton** [comment]
Seems to be much better now. I assume this has something to do with the gpu blacklist?
